Vagrant.configure("2") do |config|

	if Vagrant.has_plugin? "vagrant-vbguest"
		config.vbguest.no_install = true
		config.vbguest.auto_update = false
		config.vbguest.no_remote = true
	end

	 config.vm.define :clientenagios do |clientenagios|
		 clientenagios.vm.box = "centos/stream8"
		 clientenagios.vm.network :private_network, ip: "192.168.50.2"
		 clientenagios.vm.hostname = "cliente"
	 end

	 config.vm.define :clientenagios2 do |clientenagios2|
		 clientenagios2.vm.box = "centos/stream8"
		 clientenagios2.vm.network :private_network, ip: "192.168.50.4"
		 clientenagios2.vm.hostname = "cliente"
	 end
 
	 config.vm.define :servidornagios do |servidornagios|
		servidornagios.vm.box = "centos/stream8"
		servidornagios.vm.network :private_network, ip: "192.168.50.3"
		servidornagios.vm.hostname = "servidor"
		servidornagios.vm.network :"forwarded_port", guest: 80, host: 8090
		servidornagios.vm.network :"forwarded_port", guest: 443, host: 5568
	 end
end
